- hosts: containers_hosts
  become: true
  vars_files:
    - group_vars/VAULT
    # - group_vars/users.yml # TODO: sort out username/password for each VM
  vars:
    # - users: "{{  }}"
    - docker_users: "{{ users | map(attribute='name') | list }}"
  pre_tasks:
    - name: debug
      debug:
        msg: "{{ docker_users }}"
  roles:
    - common
    - slg.users
    - geerlingguy.docker
    - usegalaxy_eu.apptainer

