- hosts: qiime_hosts
  become: true
  vars_files:
    - group_vars/VAULT
    - group_vars/workshop_hosts.yml
    - group_vars/qiime_hosts.yml
  pre_tasks:
    - name: Attach volume to instance
      include_role:
        name: attached-volumes
    - name: create home dir on /mnt
      file:
        path: /mnt/home
        state: directory
        mode: 0755
  roles:
    - common
    - geerlingguy.pip
    - galaxyproject.miniconda
    - slg.users
  post_tasks:
    - name: Get qiime2 amplicon conda yml file
      get_url:
        url: "https://data.qiime2.org/distro/amplicon/qiime2-amplicon-2023.9-py38-linux-conda.yml"
        dest: /home/ubuntu/qiime2-amplicon-2023.9-py38-linux-conda.yml
    - name: Create environment
      command: 
        cmd: >-
          {{ miniconda_prefix }}/bin/conda env create --yes
          -n {{ env_name }} --file /home/ubuntu/qiime2-amplicon-2023.9-py38-linux-conda.yml
        creates: "{{ miniconda_prefix }}/envs/qiime2-amplicon-2023.9"

    - name: Move /tmp to other disk
      block:
        - name: Create worker tmpdir on other disk
          file:
            path: /mnt/tmpdisk
            state: directory
            owner: root
            group: root
            mode: '1777'
        - name: stat links
          stat:
            path: /tmp
          register: links
        - name: remove old tmp
          file:
            path: /tmp
            state: absent
          when: links.stat.islnk is defined and not links.stat.islnk
        - name: Link /tmp to /mnt/tmpdisk
          file:
            src: /mnt/tmpdisk
            dest: /tmp
            state: link
          become: yes
          become_user: root
          when: links.stat.islnk is defined and not links.stat.islnk
      when: attached_volumes is defined
    - name: Copy shared data to tmp
      get_url:
        url: https://swift.rc.nectar.org.au/v1/AUTH_377/public/qiime2_shared_data_20231113.tgz
        dest: /tmp/qiime2_workshop_data.tgz
    - name: Untar the shared data
      unarchive:
        src: /tmp/qiime2_workshop_data.tgz
        dest: /mnt/shared_data/
        remote_src: yes
        mode: 0755
    - name: Init conda for all users
      command: "/opt/miniconda3/bin/conda init"
      become: yes
      become_user: "{{ item.name }}"
      loop: 
        "{{ users }}"
    - name: Add conda env activation to user's .bashrc
      lineinfile:
        path: "{{ user_home }}/{{ item.name }}/.bashrc"
        line: "conda activate {{ env_name }}"
      loop:
        "{{ users }}"
    - name: Create an empty file called test_transfer.txt in each users home
      copy:
        src: files/test_transfer.txt
        dest: "{{ user_home }}/{{ item.name }}/test_transfer.txt"
        mode: 0755
      loop:
        "{{ users }}"
      
