---
- name: Update the apt repos and base OS
  apt:
      upgrade: dist
      update_cache: yes
  become: yes
  become_user: root

- name: Install some common packages
  apt:
      name: "{{ common_packages }}"
      state: latest
  become: yes
  become_user: root

- name: Install some extra packages for group
  apt:
      name: "{{ group_packages }}"
      state: latest
  become: yes
  become_user: root

- name: Make sure cloud configured hostname control is not present
  file:
    path: /etc/cloud/cloud.cfg.d/07_hostnamefix.cfg
    state: absent
  become: yes
  become_user: root

- name: Create a shared data directory
  file:
    path: "{{ shared_data_path }}"
    state: directory
    mode: 0755
  become: yes
  when: shared_data_path is defined

- name: Add hosts to /etc/hosts
  import_tasks: add_hosts.yml
  vars:
    hosts_filename: "/etc/hosts"

- name: Add extra ssh keys
  include_tasks: extra_keys.yml
  loop: "{{ extra_keys }}"
  loop_control:
    loop_var: extra_key

- name: Add ssh config
  import_tasks: ssh_config.yml
  when: ssh_config_hosts is defined